// Code generated by protoc-gen-go.
// source: m2c.proto
// DO NOT EDIT!

/*
Package m2c is a generated protocol buffer package.

It is generated from these files:
	m2c.proto

It has these top-level messages:
	M2C
*/
package atmmessage

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type M2C struct {
	Code             *int32   `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	DealPrice        *float64 `protobuf:"fixed64,2,req,name=dealPrice" json:"dealPrice,omitempty"`
	DealCount        *int32   `protobuf:"varint,3,req,name=dealCount" json:"dealCount,omitempty"`
	MarketCode       *int32   `protobuf:"varint,4,req,name=marketCode" json:"marketCode,omitempty"`
	UserName         *string  `protobuf:"bytes,5,req,name=userName" json:"userName,omitempty"`
	OrderId          *int32   `protobuf:"varint,6,req,name=orderId" json:"orderId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *M2C) Reset()         { *m = M2C{} }
func (m *M2C) String() string { return proto.CompactTextString(m) }
func (*M2C) ProtoMessage()    {}

func (m *M2C) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *M2C) GetDealPrice() float64 {
	if m != nil && m.DealPrice != nil {
		return *m.DealPrice
	}
	return 0
}

func (m *M2C) GetDealCount() int32 {
	if m != nil && m.DealCount != nil {
		return *m.DealCount
	}
	return 0
}

func (m *M2C) GetMarketCode() int32 {
	if m != nil && m.MarketCode != nil {
		return *m.MarketCode
	}
	return 0
}

func (m *M2C) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *M2C) GetOrderId() int32 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

func init() {
}
